version: "3.8"

services: 
    app:
      build: 
        context: .
        dockerfile: ./docker/Dockerfile
      ports:
        - 9000:9000
      restart: always
      depends_on:
        - postgesql
        - prometheus
        - node_exporter
        - grafana
      networks:
        - web_api
    postgesql:
      container_name: go-example-postgres
      image: postgres:12-alpine
      ports:
        - "5432:5432"
      restart: always
      env_file:
        - ".env"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DATABASE}
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      networks:
        - web_api

    prometheus:
      container_name: go-example-prometheus
      image: prom/prometheus
      restart: always
      extra_hosts:
        - "host.docker.internal:host-gateway"
      volumes:
        - ./config/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention=20d'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - '9090:9090'
      networks:
        - web_api
    
    node_exporter:
      container_name: go-example-node_exporter
      restart: always
      image: prom/node-exporter
      ports:
        - '9101:9100'
      networks:
        - web_api

    grafana:
      container_name: go-example-grafana
      restart: always
      image: grafana/grafana
      ports:
        - '3001:3000'
      networks:
        - web_api

    jaeger:
      container_name: go-example-jaeger
      restart: always
      image: jaegertracing/all-in-one:1.21
      environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      ports:
        - 5775:5775/udp
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 14268:14268
        - 14250:14250
        - 9411:9411
      networks:
        - web_api

networks:
  web_api:
    driver: bridge