DROP TABLE IF EXISTS task                CASCADE;


CREATE TABLE IF NOT EXISTS task (
   id serial NOT NULL PRIMARY KEY,
   name VARCHAR (255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP
);
